AliSoftware/Dip

CHANGELOG.md, Example/DipSampleApp/DependencyContainers.swift, Example/DipSampleApp/Providers/SWAPICommon.swift, Example/DipSampleApp/Providers/SWAPIPersonProvider.swift, Example/DipSampleApp/Providers/SWAPIStarshipProvider.swift, Example/DipSampleApp/ViewControllers/PersonListViewController.swift, Example/DipSampleApp/ViewControllers/StarshipListViewController.swift, Example/Tests/NetworkMock.swift, Example/Tests/SWAPIPersonProviderTests.swift, Example/Tests/SWAPIStarshipProviderTests.swift, README.md, Sources/Dip.swift
I noticed that at first tags were plain strings but then they changed to generics. In this pr I revert that change and here are my thoughts about that:
1. In my experience of working with DI (particularly in Obj-C with Typhoon) I've never needed named registrations. In most cases the same could be achieved by creating different containers for different environments or using runtime arguments.
2. Adding generic constraint on tag type adds type constraint on the whole container. I.e. it will be hard to add child-parent relationship between containers, or combine them in collection without introducing base protocol (what I think is useless at this point)
3. Adding generic tags limits containers flexibility and functionality. If you set it once you have to use only this type of tag inside …
=> Tags refactoring

CHANGELOG.md, Dip/Dip.xcodeproj/project.pbxproj, Dip/Dip/Definition.swift, Dip/Dip/Dip.swift, Dip/Dip/RuntimeArguments.swift, Dip/DipTests/DipTests.swift, Dip/DipTests/RuntimeArgumentsTests.swift, Example/DipSampleApp.xcodeproj/project.pbxproj, Example/DipSampleApp.xcworkspace/contents.xcworkspacedata, Example/DipSampleApp/DependencyContainers.swift, Example/DipSampleApp/Providers/SWAPIPersonProvider.swift, Example/DipSampleApp/Providers/SWAPIStarshipProvider.swift, Example/DipSampleApp/ViewControllers/PersonListViewController.swift, Example/DipSampleApp/ViewControllers/StarshipListViewController.swift, Example/Pods/Pods.xcodeproj/project.pbxproj, Example/Pods/Pods.xcodeproj/xcshareddata/xcschemes/Dip.xcscheme, Example/Tests/SWAPIPersonProviderTests.swift, Example/Tests/SWAPIStarshipProviderTests.swift, README.md
To register factories/instances it's now possible to use up to six runtime arguments. Clients can extend this number on demand.
@AliSoftware Please review it again. There are few changes that I want to note:
- I decided to remove method that registers factory that accepts tag as parameter, cause this case is covered with runtime arguments. Though I'm sure tags should stay, but they should be not used inside factories.
- Adding methods with generic arguments introduces ambiguity with `resolve` method that accepts only tag parameter, so I had to make `tag` parameter named.
=> Added support for up to six runtime arguments

CHANGELOG.md, Dip/Dip.xcodeproj/project.pbxproj, Dip/Dip/Definition.swift, Dip/Dip/Dip.h, Dip/Dip/Dip.swift, Dip/Dip/RuntimeArguments.swift, Dip/DipTests/ComponentScopeTests.swift, Dip/DipTests/DipTests.swift, Dip/DipTests/RuntimeArgumentsTests.swift, DipPlayground.playground/Pages/Circular dependencies.xcplaygroundpage/Contents.swift, DipPlayground.playground/Pages/Circular dependencies.xcplaygroundpage/timeline.xctimeline, DipPlayground.playground/Pages/Registering components.xcplaygroundpage/Contents.swift, DipPlayground.playground/Pages/Runtime arguments.xcplaygroundpage/Contents.swift, DipPlayground.playground/Pages/Scopes.xcplaygroundpage/Contents.swift, DipPlayground.playground/Pages/Shared Instances.xcplaygroundpage/Contents.swift, DipPlayground.playground/Sources/Models.swift, DipPlayground.playground/contents.xcplayground, README.md, SampleApp/DipSampleApp/Main.storyboard
This PR adds support for circular dependencies. That feature and using `resolve` inside factory block requires recursion, but lock around `resolve` method causes deadlock. I removed locking completely and propose to managed thread safety on client side.
=> Circular dependencies

CHANGELOG.md, Dip/Dip.xcodeproj/project.pbxproj, Dip/Dip.xcodeproj/xcshareddata/xcschemes/Dip.xcscheme, Dip/Dip/Dip.swift, Dip/Dip/RuntimeArguments.swift, Dip/DipTests/ComponentScopeTests.swift, Dip/DipTests/DefinitionTests.swift, Dip/DipTests/DipTests.swift, Dip/DipTests/RuntimeArgumentsTests.swift, DipPlayground.playground/Pages/Circular dependencies.xcplaygroundpage/Contents.swift, DipPlayground.playground/Pages/Resolving components.xcplaygroundpage/Contents.swift, DipPlayground.playground/Pages/Runtime arguments.xcplaygroundpage/Contents.swift, DipPlayground.playground/Pages/Scopes.xcplaygroundpage/Contents.swift, DipPlayground.playground/Pages/Shared Instances.xcplaygroundpage/Contents.swift, DipPlayground.playground/Pages/Testing.xcplaygroundpage/Contents.swift, README.md, SampleApp/DipSampleApp/Providers/SWAPIPersonProvider.swift, SampleApp/DipSampleApp/Providers/SWAPIStarshipProvider.swift, SampleApp/DipSampleApp/ViewControllers/PersonListViewController.swift, SampleApp/DipSampleApp/ViewControllers/StarshipListViewController.swift
=> Throwing errors

Dip/Dip/Definition.swift, Dip/Dip/Dip.swift, Dip/Dip/RuntimeArguments.swift, Dip/DipTests/ComponentScopeTests.swift, Dip/DipTests/DipTests.swift, DipPlayground.playground/Pages/Circular dependencies.xcplaygroundpage/Contents.swift, DipPlayground.playground/contents.xcplayground, README.md
With that PR we no more need to call `container.resolve()` with `try!` inside a factory or `resolveDependencies` block. Also convenient to use throwing constructors or any other throwing methods inside those blocks. Error will be catched by container, printed in console and then will be re-thrown.
Note: There is no way (at least for now) I can think of to be able to distinguish between throwing and not-throwing factories (thus the latest definition will override previous), except of duplicating all `register`/`resolve` methods, what I don't like at all cause it will double the number of methods in container. Taking in account that tag is an optional argument and we have support for 6 runtime arguments already (and upcoming multi-injection feature will ad 6 more methods) it will make API …
=> Throwing factories and resolve dependencies block

CHANGELOG.md, Dip/Dip.xcodeproj/project.pbxproj, Dip/Dip/AutoInjection.swift, Dip/Dip/Definition.swift, Dip/Dip/Dip.swift, Dip/DipTests/AutoInjectionTests.swift, Dip/DipTests/ComponentScopeTests.swift, DipPlayground.playground/Pages/Auto-injection.xcplaygroundpage/Contents.swift, DipPlayground.playground/Pages/Auto-injection.xcplaygroundpage/timeline.xctimeline, DipPlayground.playground/Pages/Runtime arguments.xcplaygroundpage/Contents.swift, DipPlayground.playground/Pages/Shared Instances.xcplaygroundpage/Contents.swift, DipPlayground.playground/Sources/Models.swift, DipPlayground.playground/contents.xcplayground, README.md
This PR adds auto-injection feature.
Auto-injection is a feature that let's user to get all dependencies (properties) injected by container automatically without calling `resolve` for each dependency.
- It's a more  convenient way to define circular dependencies
- It will enable automatic injection of dependencies for objects created by storyboards or nibs (as I currently imagine possible implementation of that feature) what I think is a very important feature to adopt Dip in real life projects.
This implementation provides not completely automatic resolution which seems to be impossible to implement in Swift without using ObjC runtime. So to inject dependencies user needs:
- wrap properties with special wrappers to indicate that they should be injected by container
- obtain an instance …
=> Auto-injection

CHANGELOG.md, Dip/Dip.xcodeproj/project.pbxproj, Dip/Dip/Dip.swift, Dip/DipTests/DipTests.swift, Dip/DipTests/ThreadSafetyTests.swift, README.md
As @mwoollard seems not responding I've rebased #31 on current develop and added some minor changes.
=> Add thread safety with NSRecursiveLock

Dip/Dip.xcodeproj/project.pbxproj, Dip/Dip.xcodeproj/xcshareddata/xcschemes/Dip-iOS.xcscheme, Dip/Dip/AutoInjection.swift, Dip/Dip/Definition.swift, Dip/Dip/Dip.swift, Dip/Dip/RuntimeArguments.swift, Dip/Dip/Utils.swift, Dip/DipTests/AutoInjectionTests.swift, Dip/DipTests/ComponentScopeTests.swift, Dip/DipTests/DefinitionTests.swift, Dip/DipTests/DipTests.swift, DipPlayground.playground/Pages/Auto-injection.xcplaygroundpage/Contents.swift
With this PR I try to make property auto-injection rules more strict thus safer. 
Generally property injection is less safe than constructor injection and should be used mostly in situations where dependency is optional because there is a good default implementation. Swift actually makes property injection almost unneeded with default arguments values. But still there could be cases when property injection is more correct than constructor injection (i.e. when instance is always created not by user code, but by system - that can be view controller created by storyboard).
I think that properties that should be auto-injected by Dip should be managed and created only by container. Otherwise user can replace underlying value with manually created instance that can be not fully constructed (if …
=> Auto-injection improvements

Dip/DipTests/ComponentScopeTests.swift, Dip/DipTests/DefinitionTests.swift, Sources/AutoInjection.swift, Sources/Definition.swift, Sources/Dip.swift
The problem is that instances managed using Singleton scope should not be shared between containers. But currently there is a way to register the same definition in different containers, so if we store resolved instance in definition it will be shared between those two containers. In this PR I moved storing such instances in resolved instances pool of the container that is not drained when resolve method returns. So the instances will be properly scoped to containers.
=> Singleton scope fixed

Dip/DipLinuxTests/Package.swift, Dip/DipLinuxTests/Sources/main.swift, Sources/Dip.swift, Sources/Utils.swift
Would be cool if Dip will not depend on Foundation. The only dependency now is NSRecursiveLock. So I grabbed implementation from [here](https://github.com/ReactiveX/RxSwift/blob/master/RxSwift/Concurrency/Lock.swift)
Still needs to be tested. Will try it later on virtual machine, but need to set it up first.
=> Implemented recursive lock using pthread mutex

CHANGELOG.md, Dip/Dip.xcodeproj/project.pbxproj, Dip/Dip/AutoWiring.swift, Dip/DipTests/Sources/AutoInjectionTests.swift, Dip/DipTests/Sources/AutoWiringTests.swift, Dip/DipTests/Sources/main.swift, DipPlayground.playground/Pages/Auto-injection.xcplaygroundpage/Contents.swift, DipPlayground.playground/Pages/Auto-wiring.xcplaygroundpage/Contents.swift, DipPlayground.playground/Pages/Auto-wiring.xcplaygroundpage/timeline.xctimeline, DipPlayground.playground/Pages/Shared Instances.xcplaygroundpage/Contents.swift, DipPlayground.playground/contents.xcplayground, README.md, Sources/Definition.swift, Sources/Dip.swift, Sources/RuntimeArguments.swift
Strictly speaking and comparing with other platforms (like .Net), this implementation is not exactly auto-wiring, but I can not come up with a better alternative. In (some) .Net containers auto-wiring is a container's feature to automatically resolve component as concrete type if all the arguments of it's default constructor are also concrete types without ever registering them. This implementation is different because it does not require concrete types and requires explicit registration.
Auto-wiring enables easier registration/resolution eliminating boilerplate repetitive calls to container.
With auto-wiring users can instead of this code:
```swift
container.register { RepositoryImp() as Repository }
container.register { ServiceImp(repository: try container.resolve()) as Service }
let …
```
=> Auto-wiring

Dip/DipTests/Sources/DipTests.swift, Sources/Dip.swift
Resolves #56 
+/-:
+: separation of component definition from it's dependencies usage;
+: we currently perform auto-injections after calling `resolveDependencies` block, so even at the end of `resolveDependencies` block some of the dependencies could be not yet resolved. Actually the order of these two operations does not change anything functionality-wise, but changes what instances would be reused - auto-injected or resolved manually;
-: Conformance to `Resolvable` protocol introduces dependency on Dip.
=> Added Resolvable protocol

SampleApp/DipSampleApp/DependencyContainers.swift, Sources/AutoInjection.swift, Sources/Definition.swift, Sources/Dip.swift, Sources/RuntimeArguments.swift
This offers to remove `Tag` from `register` and `resolve` APIs  in favour of `DependencyTagConvertible` protocol, which may represent Tag itself as well as any other type conforming to this protocol. 
Specifically, this allows me to use custom enums (conforming to `DependencyTagConvertible`) as tags instead of `String` or `Int` literals, making it more type-safe.
I modified SampleApp to use such an enum for tags. [see here](https://github.com/AliSoftware/Dip/compare/develop...gavrix:develop#diff-f678440884b69096a2fcf0b90b04c486R61)
At the same time, it is still possible to use `String` and `Int` literals as tags, so this PR adds more flexibility retaining existing functionality
=> DependencyTagConvertible for better typed Tags

Dip/DipTests/Sources/Utils.swift
Re-created the pull request to sort out merge issues. Note this PR breaks backward compatibility with Swift 2.1 and earlier and not validated on Linux.
=> Fix build warnings / issues from Swift 2.2

Dip/DipTests/Sources/ComponentScopeTests.swift, Sources/AutoInjection.swift, Sources/Definition.swift, Sources/Dip.swift
Resolves #63 
New scope `EagerSingleton` lets users to register components that should be instantiated by container early in the app life cycle. To define this moment new method `bootstrap` was added to `DependencyContainer`, as was suggested by @sebastian-zarzycki-es. Method call is optional. But we can print warning in `resolve` method if it is called without calling bootstrap and warn that this method can become required in future versions. 
After bootstrap is called no modifications in registered definitions can be done (no removes, no adds). 
Obvious limitation of that approach is that it can only instantiate components using factories without runtime arguments. Should not be a serious issue though. And auto-wiring is still possible. If eager singleton has dependencies or somehow …
=> EagerSingleton scope and bootstrap method

Dip/DipTests/Sources/AutoInjectionTests.swift, Sources/AutoInjection.swift
This PR provides methods to change underlying value wrapped by `Injected` and `InjectedWeak` wrappers. Mutability is controlled by containing class by choosing between `let` and `var` declaration of auto-inject property.
=> Settable auto-injected properties

Dip/Dip.xcodeproj/project.pbxproj, Dip/DipTests/ContextTests.swift, Dip/DipTests/Sources/AutoInjectionTests.swift, Dip/DipTests/Sources/AutoWiringTests.swift, Sources/AutoInjection.swift, Sources/AutoWiring.swift, Sources/Dip.swift, Sources/RuntimeArguments.swift
Container context provides some information that can be useful for debugging configurations.
The other reason to introduce it is to be able to pass the tag to resolve dependencies, used to resolve dependent instance. 
Here is an example.
Without context:
```swift
container.register { DefaultDataSource() as ViewModelDataSource }
container.register(tag: "special") { SpecialDataSource() as ViewModelDataSource }
container.register { ViewModel() as ViewModel }
.resolveDependencies { container, model in
model.dataSource = try container.resolve() as ViewModelDataSource
}
container.register(tag: "special") { ViewModel() as ViewModel }
.resolveDependencies { container, model in
model.dataSource = try container.resolve(tag: "special") as ViewModelDataSource
}
let model = try container.resolve() as …
```
=> Container context

Dip/Dip.xcodeproj/project.pbxproj
Dip doesn't appear to use any API calls that are unavailable to app extensions. Enabling this flag removes linker warning in extension targets that link against dip.
=> Enable the 'allow app extension api only' option

DipPlayground.playground/Pages/Scopes.xcplaygroundpage/Contents.swift, DipPlayground.playground/Sources/Models.swift, DipPlayground.playground/contents.xcplayground, Sources/Definition.swift, Sources/Dip.swift, Sources/Utils.swift, Tests/Dip/AutoWiringTests.swift, Tests/Dip/ComponentScopeTests.swift, Tests/Dip/DipTests.swift
This scope can be usefull when there is a need to recreate objects graph at runtime without reseting container and registering all components again.
For example when user changes a language inside application and all its components (UI and business logic) should be recreated. 
It is analogous to TyphoonScopeWeakSingleton scope present in Typhoon
=> WeakSingleton scope

Dip/DipTests/TypeForwardingTests.swift, DipPlayground.playground/Pages/Auto-injection.xcplaygroundpage/Contents.swift, DipPlayground.playground/Pages/Auto-wiring.xcplaygroundpage/Contents.swift, DipPlayground.playground/Pages/Circular dependencies.xcplaygroundpage/Contents.swift, DipPlayground.playground/Pages/Containers Collaboration.xcplaygroundpage/Contents.swift, DipPlayground.playground/Pages/Resolving components.xcplaygroundpage/Contents.swift, DipPlayground.playground/Pages/Runtime arguments.xcplaygroundpage/Contents.swift, DipPlayground.playground/Pages/Scopes.xcplaygroundpage/Contents.swift, DipPlayground.playground/Pages/Testing.xcplaygroundpage/Contents.swift, DipPlayground.playground/Pages/Type Forwarding.xcplaygroundpage/Contents.swift, README.md, SampleApp/DipSampleApp/DependencyContainers.swift, Sources/AutoInjection.swift, Sources/AutoWiring.swift, Sources/Definition.swift, Sources/Dip.swift, Sources/RuntimeArguments.swift, Sources/TypeForwarding.swift, Tests/Dip/AutoInjectionTests.swift, Tests/Dip/AutoWiringTests.swift, Tests/Dip/ComponentScopeTests.swift, Tests/Dip/ContextTests.swift, Tests/Dip/DefinitionTests.swift, Tests/Dip/DipTests.swift, Tests/Dip/RuntimeArgumentsTests.swift, Tests/Dip/ThreadSafetyTests.swift
With Swift3 API guidelines in mind here is what I propose to rename in public API:
1. `ObjectGraph` -> `Shared`, `Prototype` -> `Unique`. These names will make it more clear how these scopes affect instances
2. `resolveDependencies` -> `resolvingProperties`
3. `DefinitionKey` properties: `protocolType` -> `type`, `associatedTag` -> `tag`, `argumentsType` -> `typeOfArguments`. Additional words in original names do not add any value to understanding meaning of these properties.
4.  `resolve` method parameter `withArguments` -> `arguments`
5. switch places for `scope` and `tag` parameters in `register` method. This does not break API in Swift2 but with Swift 3 will require to follow the order from declaration (SE-0060). `register(.Shared, tag: "some")` looks nicer than `register(tag: "some", …
=> Grand renaming

Sources/Dip.swift, Sources/RuntimeArguments.swift
With that it is possible to register abstractions using methods of concrete type. Without it it is only possible to register concrete types using method instead of closure, like this:
```swift
container.register(factory: ServiceImp.init)
try container.resolve() as Service //fails
try container.resolve() as ServiceImp //succeeds
```
With explicit type parameter it is possible to register abstractions the same way as when using closures:
```swift
container.register(type: Service.self, factory: ServiceImp.init)
try container.resolve() as Service //succeeds
try container.resolve() as ServiceImp //fails
```
`type` parameter is optional and by default is inferred from the return type of the factory. It is even not used in during registration, it just provides compiler with explicit type to …
=> Optional type parameter in register methods

Dip/DipTests/TypeForwardingTests.swift, Sources/AutoWiring.swift, Sources/Definition.swift, Sources/Dip.swift, Sources/TypeForwarding.swift
- removed deprecation annotation for register(_:type:tag:)
- added removing previously registered definition when overriding (for proper cleanup)
- fixed calling resolvingProperties set after registering type-forwarding
- improved tests and code comments
=> Improved type forwarding

Sources/AutoInjection.swift, Sources/Dip.swift, Sources/TypeForwarding.swift, Tests/Dip/AutoInjectionTests.swift, Tests/Dip/DipTests.swift
* Fixed auto-injection to ensure that inherited auto-injected properties are resolved.
* Added `resolveDependencies(_:DependencyContainer)` method in `Resolvable` protocol for reusing dependencies resolution when inheriting.
Resolves #69
=> Properly handling inheritance

DipPlayground.playground/Pages/Auto-wiring.xcplaygroundpage/Contents.swift, Sources/AutoInjection.swift, Sources/AutoWiring.swift, Sources/Definition.swift
To simplify implementation of auto-wiring and remove some indirection in what definition will be used to auto-wire components container will form now on always use definition with a factory that accepts most number of arguments and matches tag (if provided) instead of iterating over definitions for the same type in order of decreasing arguments number. In practice in most of the cases there will be one definition per components, so that just adds computational and code complexity. 
Rarely there could be ambiguous definitions when the same component is registered for the same tag with the same number but different types of runtime arguments.
=> Simplified auto-wiring

Sources/Definition.swift
Apple Swift version 3.0 (swiftlang-800.0.46.2 clang-800.0.38)
The GM compiler introduces compile error this submission addresses.
=> Fix compile error when building with Xcode8/Swift 3 GM

DipPlayground.playground/Pages/Auto-injection.xcplaygroundpage/Contents.swift, Sources/AutoInjection.swift, Tests/DipTests/AutoInjectionTests.swift, Tests/DipTests/AutoWiringTests.swift, Tests/DipTests/DipTests.swift, Tests/DipTests/RuntimeArgumentsTests.swift, Tests/DipTests/ThreadSafetyTests.swift
Relates to #107 
SR-2144 was fixed in Xcode 8 GM
SR-2282 was fixed in Dip by checking for the name of property type for IUO and ignoring such properties to avoid accessing it's value
SR-2143 still not resolved but is not very critical
=> Fixed Swift 3 issues

Sources/Dip.swift, Tests/DipTests/ComponentScopeTests.swift
when underlying instance was already released
Resolves #128
=> Fixed reusing instances for weak singletons

.travis.yml, Dip/Dip.xcodeproj/project.pbxproj, Sources/AutoInjection.swift, Sources/AutoInjection_swift2.swift, Sources/AutoWiring.swift, Sources/Compatibility.swift, Sources/ComponentScope.swift, Sources/ComponentScope_swift2.swift, Sources/Definition.swift, Sources/Dip.swift, Sources/DipError.swift, Sources/DipError_swift2.swift, Sources/Register.swift, Sources/Register_swift2.swift, Sources/Resolve.swift, Sources/Resolve_swift2.swift, Sources/RuntimeArguments_swift2.swift, Sources/TypeForwarding.swift, Sources/TypeForwarding_swift2.swift, Sources/Utils.swift, Tests/DipTests/AutoInjectionTests.swift
This PR brings support for both Swift 2.3 and Swift 3 so that there is no need to keep a separate brunch for Swift 2.3 and it will be easier to drop it's support as part of 2.3 specific implementation is moved to separate source files.
=> Swift 2.3 compatibility

Sources/Definition.swift
This change is backwards-compatible fix for new warning in Xcode 8.3/ Swift 3.1 mentioned in #144
=> Fix swift 3.1 warning

Sources/Utils.swift
This is a copy of Swinject feature: https://github.com/Swinject/Swinject/blob/master/Sources/Container.Logging.swift
It will allow user to redirect Dip logs to file and/or some custom logger if it's required
=> Enable use of custom or no logging function

Sources/Definition.swift, Sources/Dip.swift
=> Added Equatable conformance on the site of declaration

Sources/Dip.swift, Sources/Register.swift, Sources/Resolve.swift, Tests/DipTests/DipTests.swift
=> Fix: containers with common collaborator share resolved instances for their own definitions

Sources/Dip.swift
I have an issue with a configuration using a main container created at startup with many factories and bootstrapped and a secondary container that it's dynamically configured during the app lifetime. I sometimes get a crash when resolving weak singletons. The crash points that it can't cast the resolved instance to the required type. This indicates that the resolved instances caches are corrupted at some point.
This same container setup works perfectly with version 5.1 of Dip but I need swift 4 for the next version of the app.
Signed-off-by: Antonio Cabezuelo Vivo <antonio@tapsandswipes.com>
=> Fix crash with colaborator containers and weak singletons

Sources/Utils.swift
ImplicitlyUnwrappedOptional was already deprecated and it has been removed in swift 4.2
If you don't remove this extension Dip won't compile with Swift 4.2
=> Removed extension of ImplicitlyUnwrappedOptional

Dip/Dip.xcodeproj/xcshareddata/xcschemes/Dip.xcscheme
This causes issues whenn linking as a static library using Carthage:
```
Undefined symbols for architecture x86_64:
"___llvm_profile_runtime", referenced from:
___llvm_profile_runtime_user in Dip(Utils.o)
___llvm_profile_runtime_user in Dip(Definition.o)
___llvm_profile_runtime_user in Dip(ComponentScope.o)
___llvm_profile_runtime_user in Dip(AutoWiring.o)
___llvm_profile_runtime_user in Dip(Dip.o)
___llvm_profile_runtime_user in Dip(Register.o)
___llvm_profile_runtime_user in Dip(Resolve.o)
```
=> Disable gathering code coverage

Dip/Dip.xcodeproj/project.pbxproj
Apple now requires that watchOS deployment target are minimum locked at 3.0 version.
https://forums.developer.apple.com/thread/108853
Could you create a tag after merging so we can use it on Carthage?
Thank you!
=> Bump watchos deployment target to 3.0
